#!/bin/bash

# The backup server
BS_USER="pi"
BS_IP="192.168.0.129"
BS_PATH="/mnt/archive/$(hostname)"

# The backup location
BU_LOC="$BS_USER@$BS_IP:$BS_PATH::$(date -I)"

# The backup sources
BU_INCLUDE="$HOME"

colored_output -t i -m "starting backup at $BU_LOC"
borg create --progress --exclude-from backupexcludes.txt $BU_LOC $BU_INCLUDE 
colored_output -t i -m "backup finished. Exiting"
