#!/bin/bash

colored_output -t i -m "Copying backup key."
pass Backup/$(hostname) | wl-copy

# The backup server
BS_USER="pi"
BS_IP="rhea.coijanovic.com"
BS_PATH="/mnt/archive/$(hostname)"

# The backup location
BU_LOC="$BS_USER@$BS_IP:$BS_PATH::$(date -I)"

# The backup sources
BU_INCLUDE="$HOME"
BU_EXCLUDE="$HOME/Code/scripts/backupexcludes.txt"

colored_output -t i -m "starting backup at $BU_LOC"
borg create --progress --exclude-from $BU_EXCLUDE $BU_LOC $BU_INCLUDE 
colored_output -t i -m "backup finished. Exiting"
