#! /bin/sh

# rhea's ip address
server=192.168.0.129                    

# [TODO] add ping test

mount $server:/mnt/data/Documents       $HOME/Documents
mount $server:/mnt/data/Pictures        $HOME/Pictures
mount $server:/mnt/data/Music           $HOME/Music
