#! /bin/sh

# rhea's ip address
server=192.168.0.129                    
user=$USER


# [TODO] add ping test
colored_output -t i -m "Pinging rhea"

# mount
colored_output -t i -m "Mounting NFS shares"
sudo mount $server:/mnt/data/Documents       $HOME/Documents
sudo mount $server:/mnt/data/Pictures        $HOME/Pictures
sudo mount $server:/mnt/data/Music           $HOME/Music

# [TODO] test mounts

colored_output -t i -m "Exiting"
exit
