#! /bin/bash

od=$(pwd)
cd $HOME/Notes

new () { 
    now=$(date +%Y-%m-%d-%H:%M)
    vi $now.md
}

push () {
    git add -A
    git commit -m "updated note"
    git push
    colored_output -t i -m "Saved notes."
}
if [ -z "$1" ]
then
      new
else
      push
fi
cd $od
