#! /bin/bash
# Interactivly select a password from pass using fzf and copy it with wl-copy

od=$(pwd)
cd $HOME/.password-store
p=$(fd -t f . | cut -d "." -f1 | fzf)
file=$(gpg --pinentry-mode loopback -d /home/christoph/.password-store/Ikea.gpg)
pass -c $p
cd $od
