#! /bin/bash
# Interactivly select a password from pass using fzf and copy it with wl-copy

od=$(pwd)
cd $HOME/.password-store
p=$(fd -t f . | fzf | cut -d "." -f1)
pass $p | head -n 1 | wl-copy
cd $od
