#! /bin/sh

# This script sets up common programm combinations using sway

# Open all work-related programms and moves them to their assigned workspaces
work () {
    colored_output -t i -m "Setting up Work." 
    dock

    riot_url="https://i62riot.tm.kit.edu"
    board_url="https://i63board.tm.kit.edu/?controller=BoardViewController\&action=show\&project_id=6#"

    sway exec "alacritty --class side"
    swaymsg [app_id="side"] resize set 33 ppt

    sway exec "firefox-wayland $riot_url $board_url"
    sway for_window [app_id="firefox"] move workspace 2

    sway exec "thunderbird"
    sway for_window [class="Thunderbird"] move workspace 3
    pass KIT/Christoph/Thunderbird | wl-copy
    colored_output -t i -m "Thunderbird password copied to clipboard."

    sway exec "okular"
    sway for_window [app_id="okular"] move workspace 6

    sway exec "alacritty --class cmus -e 'cmus'"
    sway for_window [app_id="cmus"] move workspace 7
    colored_output -t s -m "Finished."
}

# Open chromium with tabs needed for the board meeting and move to assigned workspace
board () {
    colored_output -t i -m "Setting up Board Meeting." 

    board_url="https://i63board.tm.kit.edu/?controller=BoardViewController\&action=show\&project_id=6#"
    bbb_url="https://i62bbb.tm.kit.edu/b/tho-3wz-23e"

    sway exec "chromium-browser $board_url $bbb_url"
    sway for_window [class="Chromium-browser"] move workspace 4
    sway workspace 4

    colored_output -t s -m "Finished."
}

# Open signal
signal () {
    colored_output -t i -m "Setting up Signal"

    sway exec "flatpak run org.signal.Signal"
    sway for_window [class="Signal"] move workspace 8
    sway workspace 8

    colored_output -t s -m "Finished."
}

home () {
    colored_output -t i -m "Setting up Home." 

    dock
    
    sway exec "firefox-wayland"
    sway for_window [app_id="firefox"] move workspace 2

    mount_rhea

    colored_output -t s -m "Finished."
}

shopt -s extglob
case "$1" in
    ?(w|wo|wor|work) )
        work ;;
    ?(b|bo|boa|boar|board) )
        board ;;
    ?(s|si|sig|sign|signa|signal) )
        signal ;;
    ?(h|ho|hom|home) )
        home ;;
    *)
        colored_output -t e -m "Unkown Option. Available: setup [work|board|signal]"
esac
