#! /bin/sh

# This script sets up common programm combinations using sway

# Open all work-related programms and moves them to their assigned workspaces
work () {
    colored_output -t i -m "Setting up Work." 
    sed -i -e "s/size: 13/size: 11/g" .config/alacritty/alacritty.yml

    riot_url="https://i62riot.tm.kit.edu"
    board_url="https://i63board.tm.kit.edu/?controller=BoardViewController\&action=show\&project_id=6#"

    sway exec "alacritty"
    sway resize set 33 ppt

    sway exec "firefox-wayland $riot_url $board_url"
    sway for_window [app_id="firefox"] move workspace 2

    sway exec "thunderbird"
    sway for_window [class="Thunderbird"] move workspace 3

    sway exec "okular"
    sway for_window [app_id="okular"] move workspace 6

    sway exec "alacritty --class cmus -e 'cmus'"
    sway for_window [app_id="cmus"] move workspace 7
    colored_output -t s -m "Finished."
}

# Open chromium with tabs needed for the board meeting and move to assigned workspace
board () {
    colored_output -t i -m "Setting up Board Meeting." 

    board_url="https://i63board.tm.kit.edu/?controller=BoardViewController\&action=show\&project_id=6#"
    bbb_url="https://i62bbb.tm.kit.edu/b/tho-3wz-23e"

    sway exec "chromium-browser $board_url $bbb_url"
    sway for_window [class="Chromium-browser"] move workspace 4
    sway workspace 4

    colored_output -t s -m "Finished."
}

# Open signal
signal () {
    colored_output -t i -m "Setting up Signal"

    sway exec "flatpak run org.signal.Signal"
    sway for_window [class="Signal"] move workspace 8
    sway workspace 8

    colored_output -t s -m "Finished."
}

home () {
    colored_output -t i -m "Setting up Home." 

    swaymsg -t get_outputs | rg "DP-3"
    if [ $? -eq "1" ]
    then
        colored_output -t i -m "Detected external monitor."
        sway output DP-3 mode 3840x2160@29.981001Hz
        sed -i -e "s/size: 11/size: 13/g" .config/alacritty/alacritty.yml
    fi

    bluetoothctl connect E0:EB:40:D0:C8:21
    while [ $? -neq "0" ]
    do
        colored-output -t e -m "Could not connect keyboard."
        read -r -p "Try again? [y/n] " input
         
        case $input in
            [yY][eE][sS]|[yY] )
                bluetoothctl connect E0:EB:40:D0:C8:21 ;;
            [nN][oO]|[nN] )
                break ;;
            * )
                colord_output -t e -m "Unknown input." ;;
        esac
    done
    
    sway exec "firefox-wayland"
    sway for_window [app_id="firefox"] move workspace 2

    mount_rhea

    colored_output -t s -m "Finished."
}

shopt -s extglob
case "$1" in
    ?(w|wo|wor|work) )
        work ;;
    ?(b|bo|boa|boar|board) )
        board ;;
    ?(s|si|sig|sign|signa|signal) )
        signal ;;
    ?(h|ho|hom|home) )
        home ;;
    *)
        colored_output -t e -m "Unkown Option. Available: setup [work|board|signal]"
esac
