#! /bin/sh

# This script sets up common programm combinations using sway

# Open all work-related programms and moves them to their assigned workspaces
work () {
    colored_output -t i -m "Setting up Work." 

    sudo mount -a
    pass KIT/Saskia/thunderbird | wl-copy


    sway exec "firefox-wayland"
    sway for_window [app_id="firefox"] move workspace 2

    sway exec "thunderbird"
    sway for_window [class="Thunderbird"] move workspace 3

    sway exec "alacritty --class cmus -e 'cmus'"
    sway for_window [app_id="cmus"] move workspace 4
    colored_output -t s -m "Finished."
    
    sway exec "okular"

    colored_output -t s -m "Finished."
}

shopt -s extglob
case "$1" in
    ?(w|wo|wor|work) )
        work ;;
    *)
        colored_output -t e -m "Unkown Option. Available: setup_saskia work"
esac

