#! /bin/bash
# todo is a plain-text minimal networked todo app

remote="rhea"
tododir="/mnt/data/Documents/todo"
# adds a new todo
add () {
    colored_output -t i -m "Adding a new TODO"
    read -p "What needs to be done? " content
    read -p "How urgent is it? [0-5] " prio
    data=$(jq -n \
        --arg c "$content" \
        --arg p "$prio" \
        '{content: $c, prio: $p}')
    curl -H "Content-Type: application/json" \
        -d "$data" \
        http://rhea.local:8000/add
}
show () {
    curl http://rhea.local:8000/tasks
}
edit () {
    scp rhea:$tododir/todo /tmp/todo
    nvim /tmp/todo
    scp /tmp/todo rhea:$tododir/
    rm /tmp/todo
}
if [ "$1" == "add" ]; then
    add
elif [ "$1" == "edit" ]; then
    edit
else
    show
fi
